# Generated by Django 2.2 on 2021-04-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_add_event',
            field=models.ManyToManyField(related_name='join_events', to='events.User'),
        ),
    ]
